version: "3.9"

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-16}
    container_name: ${POSTGRES_CONTAINER_NAME:-docker-postgres}
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5